services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    command: npm run start:dev
    restart: "always"